var json_prenote=null,Prenota={list:null,pagingTop:null,pagingBottom:null,pagingText:null,pagingInfo:{currentPage:0,totalCount:0,perPage:cfg.itemsPerPage},init:function(){this.list=document.getElementById("list");this.pagingTop=document.getElementById("paging_top");this.pagingBottom=document.getElementById("paging_bottom");this.pagingText=document.getElementById("paging_text");this.pagingTop.onclick=function(){"disabled"!=this.className&&Prenota.mostrarProductos(Prenota.pagingInfo.currentPage-1)};
this.pagingBottom.onclick=function(){"disabled"!=this.className&&Prenota.mostrarProductos(Prenota.pagingInfo.currentPage+1)};for(j=0;j<this.pagingInfo.perPage;j++)this.list.children[j].children[1].onclick=this.removeProduct;for(j=0;j<this.pagingInfo.perPage;j++)this.list.children[j].children[0].onclick=this.productDetails;this.mostrarProductos(0)},mostrarProductos:function(a){var c=productos;this.pagingInfo.currentPage=a;this.pagingInfo.totalCount=0<c.length?c.length:1;this.pagingText.innerText=a+
1+"/"+Math.ceil(this.pagingInfo.totalCount/this.pagingInfo.perPage);for(var b=0,d=c.length-1-a*this.pagingInfo.perPage;0<=d&&b<this.pagingInfo.perPage;d--,b++)this.list.children[b].children[0].children[0].innerHTML=c[d].Description,this.list.children[b].children[0].children[1].innerHTML="<div>$"+c[d].Price.toFixed(2)+"</div> <div>Cant: "+c[d].Quantity+"</div>",this.list.children[b].children[1].id=d,this.list.children[b].children[0].id=d,this.list.children[b].style.setProperty("visibility","visible");
if(b<this.pagingInfo.perPage)for(b;b<this.pagingInfo.perPage;b++)this.list.children[b].children[0].children[0].innerHTML="Empty",this.list.children[b].style.setProperty("visibility","hidden");a+1==Math.ceil(this.pagingInfo.totalCount/this.pagingInfo.perPage)?this.pagingBottom.className="disabled":this.pagingBottom.className="enabled";this.pagingTop.className=0==a?"disabled":"enabled"},removeProduct:function(a){a=parseInt(a.currentTarget.id);productos.splice(a,1);window.localStorage.setItem("products",
JSON.stringify(productos));Prenota.mostrarProductos(0)},calcularTotal:function(){for(var a=new Decimal(0),c=0;c<productos.length;c++)var b=(new Decimal(productos[c].Price)).times(productos[c].Quantity),a=a.plus(b);return a.toNumber().toFixed(2)},cantidadTotal:function(){for(var a=new Decimal(0),c=0,b=0;b<productos.length;b++)a=a.plus(productos[b].Quantity),productos[b].unitDecimals>c&&(c=productos[b].unitDecimals);return a.toNumber().toFixed(c)},productDetails:function(a){a=parseInt(a.currentTarget.id);
window.localStorage.setItem("details",a);window.location="product_details.html"}};asl.title("Prenota");asl.back(function(){window.location="scan_product.html"});asl.events.subscribe(asl.events.types.exit,function(){asl.badge(null);"function"==typeof asl.lock&&asl.lock(null)});asl.events.subscribe(asl.events.types.loaded,function(){Prenota.init();selectedPrinter=JSON.parse(window.localStorage.getItem("selectedPrinter"));null!==selectedPrinter&&(window.localStorage.removeItem("selectedPrinter"),save())});
asl.options([{title:"Ver total",callback:function(){alert("Total: $"+Prenota.calcularTotal())}},{title:"Imprimir prenota",callback:function(){window.localStorage.setItem("nueva_prenota",!0);window.location="printers_list.html"}},{title:"Imprimir \u00faltima prenota",callback:function(){window.localStorage.removeItem("nueva_prenota");window.location="printers_list.html"}},{title:"Eliminar prenota",callback:function(){confirm("\u00bfSeguro que desea eliminar la prenota?",function(a){a&&delete_prenote()})}},
{title:"Salir",callback:exit}]);function delete_prenote(){window.localStorage.removeItem("products");window.localStorage.removeItem("bhasName");window.localStorage.removeItem("sclientName");productos.length=0;Prenota.mostrarProductos(0)}
function save(){try{var a=window.localStorage.getItem("prenote");if(null!=a)window.localStorage.removeItem("prenote"),json_prenote=a;else if(window.localStorage.getItem("nueva_prenota")){var c=Prenota.calcularTotal(),b=Prenota.cantidadTotal(),d=JSON.parse(window.localStorage.getItem("nCotizationNumber")),e=JSON.parse(window.localStorage.getItem("sclientName"));window.localStorage.removeItem("answerOfCotization");window.localStorage.removeItem("nCotizationNumber");var f=new oPrenote({total:c,id_employee:user.ID,
employeeLogin:user.Login,product:productos,narticles:b,employeeName:user.Name,printer:selectedPrinter,cotizationNumber:d,clientName:e});json_prenote=JSON.stringify(f)}else json_prenote=window.localStorage.getItem("lastPrenote");save_prenote()}catch(g){alert(g.message)}}function exit(){confirm("Esta seguro que quiere salir de la aplicaci\u00f3n?",function(a){try{a&&asl.exit()}catch(c){alert(c)}})}
function save_prenote(){var a;a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var c=a.responseText.trim();try{var b=JSON.parse(c);if(b){var d=b.status,e=b.message||"",f=d.printed,g=d.validClient;if(d.saved)if(prenote=new oPrenote(d.prenote||{}),!g)prenote.changeClient=!0,window.localStorage.setItem("prenote",JSON.stringify(prenote)),confirm(e,function(a){a&&askClientName()});else if(!f)window.localStorage.setItem("prenote",
JSON.stringify(prenote)),alert("No se pudo imprimir el ticket.");else{if("object"==typeof prenote&&(window.localStorage.removeItem("prenote"),alert("Ticket impreso con folio: "+prenote.folio),window.localStorage.getItem("nueva_prenota"))){var h=JSON.stringify(prenote);window.localStorage.setItem("lastPrenote",h);delete_prenote()}}else alert("No se pudo guardar el ticket: "+e)}else alert("No se obtuvo respuesta del servidor.")}catch(k){alert("Error: "+c)}}};a.open("POST","php/db/save_ticket.php",!0);
a.setRequestHeader("Content-Type","application/x-www-form-urlencoded charset=utf-8");a.send("prenote="+json_prenote)}function saveName(a,c){hasName=!0;var b=JSON.stringify(c),d=JSON.stringify(hasName);window.localStorage.setItem("sclientName",b);window.localStorage.setItem("bhasName",d);prenote.clientName=c;prenote.changeClient=!0;json_prenote=JSON.stringify(prenote);save_prenote()}
function askClientName(){asl.showKeyboard({inputId:"askClientName",title:"Ingresa el cliente.",type:"text",scanner:!0,back:!1},saveName)};