var json_prenote=null,Prenota={list:null,pagingTop:null,pagingBottom:null,pagingText:null,pagingInfo:{currentPage:0,totalCount:0,perPage:cfg.itemsPerPage},init:function(){this.list=document.getElementById("list");this.pagingTop=document.getElementById("paging_top");this.pagingBottom=document.getElementById("paging_bottom");this.pagingText=document.getElementById("paging_text");this.pagingTop.onclick=function(){"disabled"!=this.className&&Prenota.mostrarProductos(Prenota.pagingInfo.currentPage-1)};
this.pagingBottom.onclick=function(){"disabled"!=this.className&&Prenota.mostrarProductos(Prenota.pagingInfo.currentPage+1)};for(j=0;j<this.pagingInfo.perPage;j++)this.list.children[j].children[1].onclick=this.removeProduct;for(j=0;j<this.pagingInfo.perPage;j++)this.list.children[j].children[0].onclick=this.productDetails;this.mostrarProductos(0)},mostrarProductos:function(a){var b=productos;this.pagingInfo.currentPage=a;this.pagingInfo.totalCount=0<b.length?b.length:1;this.pagingText.innerText=a+
1+"/"+Math.ceil(this.pagingInfo.totalCount/this.pagingInfo.perPage);for(var c=0,d=b.length-1-a*this.pagingInfo.perPage;0<=d&&c<this.pagingInfo.perPage;d--,c++)this.list.children[c].children[0].children[0].innerHTML=b[d].Description,this.list.children[c].children[0].children[1].innerHTML="<div>$"+b[d].Price.toFixed(2)+"</div> <div>Cant: "+b[d].Quantity+"</div>",this.list.children[c].children[1].id=d,this.list.children[c].children[0].id=d,this.list.children[c].style.setProperty("visibility","visible");
if(c<this.pagingInfo.perPage)for(c;c<this.pagingInfo.perPage;c++)this.list.children[c].children[0].children[0].innerHTML="Empty",this.list.children[c].style.setProperty("visibility","hidden");this.pagingBottom.className=a+1==Math.ceil(this.pagingInfo.totalCount/this.pagingInfo.perPage)?"disabled":"enabled";this.pagingTop.className=0==a?"disabled":"enabled"},removeProduct:function(a){a=parseInt(a.currentTarget.id);productos.splice(a,1);window.localStorage.setItem("products",JSON.stringify(productos));
Prenota.mostrarProductos(0)},calcularTotal:function(){for(var a=new Decimal(0),b=0;b<productos.length;b++)var c=(new Decimal(productos[b].Price)).times(productos[b].Quantity),a=a.plus(c);return a.toNumber().toFixed(2)},cantidadTotal:function(){for(var a=new Decimal(0),b=0,c=0;c<productos.length;c++)a=a.plus(productos[c].Quantity),productos[c].unitDecimals>b&&(b=productos[c].unitDecimals);return a.toNumber().toFixed(b)},productDetails:function(a){a=parseInt(a.currentTarget.id);window.localStorage.setItem("details",
a);window.location="product_details.html"}};asl.title("Prenota");asl.back(function(){window.location="scan_product.html"});asl.events.subscribe(asl.events.types.exit,function(){asl.badge(null);"function"==typeof asl.lock&&asl.lock(null)});asl.events.subscribe(asl.events.types.loaded,function(){Prenota.init();selectedPrinter=JSON.parse(window.localStorage.getItem("selectedPrinter"));null!==selectedPrinter&&(window.localStorage.removeItem("selectedPrinter"),save())});
asl.options([{title:"Ver total",callback:function(){alert("Total: $"+Prenota.calcularTotal())}},{title:"Imprimir prenota",callback:function(){window.localStorage.setItem("nueva_prenota",!0);window.location="printers_list.html"}},{title:"Imprimir \u00faltima prenota",callback:function(){window.localStorage.removeItem("nueva_prenota");window.location="printers_list.html"}},{title:"Eliminar prenota",callback:function(){confirm("\u00bfSeguro que desea eliminar la prenota?",function(a){a&&delete_prenote()})}},
{title:"Salir",callback:exit}]);function delete_prenote(){window.localStorage.removeItem("products");window.localStorage.removeItem("bhasName");window.localStorage.removeItem("sclientName");productos.length=0;Prenota.mostrarProductos(0)}
function save(){try{var a=window.localStorage.getItem("prenote");if(null!=a)window.localStorage.removeItem("prenote"),json_prenote=a;else if(window.localStorage.getItem("nueva_prenota")){var b=Prenota.calcularTotal(),c=Prenota.cantidadTotal(),d=JSON.parse(window.localStorage.getItem("nCotizationNumber")),e=JSON.parse(window.localStorage.getItem("sclientName"));window.localStorage.removeItem("answerOfCotization");window.localStorage.removeItem("nCotizationNumber");var f=new oPrenote({total:b,id_employee:user.ID,
employeeLogin:user.Login,product:productos,narticles:c,employeeName:user.Name,printer:selectedPrinter,cotizationNumber:d,clientName:e});json_prenote=JSON.stringify(f)}else if(json_prenote=window.localStorage.getItem("lastPrenote"),null!=json_prenote){var g=JSON.parse(json_prenote);g.printer=selectedPrinter;json_prenote=JSON.stringify(g)}save_prenote()}catch(h){alert(h.message)}}
function exit(){confirm("Esta seguro que quiere salir de la aplicaci\u00f3n?",function(a){try{a&&asl.exit()}catch(b){alert(b)}})}
function save_prenote(){var a;a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var b=a.responseText.trim();try{var c=JSON.parse(b);if(c){var d=c.status,e=c.message||"",f=d.printed,g=d.validClient;if(d.saved)if(prenote=new oPrenote(d.prenote||{}),!g)prenote.changeClient=!0,window.localStorage.setItem("prenote",JSON.stringify(prenote)),confirm(e,function(a){a&&askClientName()});else if(!f){var h=JSON.stringify(prenote);
window.localStorage.setItem("prenote",h);printPrenote(h)}else{if("object"==typeof prenote&&(window.localStorage.removeItem("prenote"),alert("Ticket impreso con folio: "+prenote.folio),window.localStorage.getItem("nueva_prenota"))){var k=JSON.stringify(prenote);window.localStorage.setItem("lastPrenote",k);delete_prenote()}}else alert("No se pudo guardar el ticket: "+e)}else alert("No se obtuvo respuesta del servidor.")}catch(l){alert("Error: "+b)}}};a.open("POST","php/db/save_ticket.php",!0);a.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded; charset=utf-8");a.send("prenote="+encodeURIComponent(json_prenote))}
function printPrenote(a){var b;b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var a=b.responseText.trim();try{var d=JSON.parse(a),e=JSON.parse(window.localStorage.getItem("prenote"));if(1==d){if(window.localStorage.removeItem("prenote"),alert("Ticket impreso con folio: "+e.folio),window.localStorage.getItem("nueva_prenota")){var f=JSON.stringify(e);window.localStorage.setItem("lastPrenote",f);delete_prenote()}}else alert("No se pudo imprimir la prenota: "+
e.folio+".")}catch(g){alert("Error: "+a)}}};b.open("POST",cfg.uri+"PrintPrenote/",!0);b.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=utf-8");b.send("jsonPrenote="+encodeURIComponent(a))}function saveName(a,b){hasName=!0;var c=JSON.stringify(b),d=JSON.stringify(hasName);window.localStorage.setItem("sclientName",c);window.localStorage.setItem("bhasName",d);prenote.clientName=b;prenote.changeClient=!0;json_prenote=JSON.stringify(prenote);save_prenote()}
function askClientName(){asl.showKeyboard({inputId:"askClientName",title:"Ingresa el cliente.",type:"text",scanner:!0,back:!1},saveName)}function sendDebugInfo(a){var b;b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");b.onreadystatechange=function(){};b.open("GET","php/debug_info.php?debug_info="+a,!0);b.send()};